/articlenotfound.do=mvc.ArticleNotFoundHandler
/hello.do=mvc.HelloHandler
/list.do=mvc.ListHandler
/listview.do=mvc.ListViewHandler
/writeForm.do=mvc.WriteFormHandler
/write.do=mvc.WriteHandler
/read.do=mvc.ReadHandler
/readview.do=mvc.ReadViewHandler
/readform.do=mvc.ReadFormHandler
/reply.do=mvc.ReplyHandler
/replyform.do=mvc.ReplyFormHandler
/replysuccess.do=mvc.ReplySuccessHandler
/replyerror.do=mvc.ReplyErrorHandler
/upddateerror.do=mvc.UpdateErrorHandler
/updateform.do=mvc.UpdateFormHandler
/update.do=mvc.UpdateHandler
/deleteform.do=mvc.DeleteFormHandelr
/deleteerror.do=mvc.DeleteErrorHandler
/deletesuccess.do=mvc.DeleteSuccessHandler
/delete.do=mvc.DeleteHandler
/deleteform.do=mvc.DeleteFormHandler
/errorview.do=mvc.EroorViewHandler

